name: Tweet Bot

on:
  schedule:
    - cron: '22 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Asegúrate de que es v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Añadir esta línea para asegurar Node.js 20
        with:
          node-version: '20'

      - name: Check Node.js version  # Este paso verifica la versión de Node.js
        run: node -v

      - name: Set up Python
        uses: actions/setup-python@v4  # Asegúrate de que es v4
        with:
          python-version: '3.x'

          
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install tweepy
        
      - name: Run the bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweet_bot.py
