name: Tweet Bot

on:
  workflow_dispatch:  # Esto permite ejecutar la acción manualmente
  schedule:
    - cron: '0 21 * * *'  # Esto lo ejecutará a las 9 AM y 9 PM UTC

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Asegúrate de que es v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Añadir esta línea para asegurar Node.js 20
        with:
          node-version: '20'

      - name: Check Node.js version  # Este paso verifica la versión de Node.js
        run: node -v

      - name: Set up Python
        uses: actions/setup-python@v4  # Asegúrate de que es v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Run tweet bot
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python tweet_bot.py
